name: Package checks

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: flutter/flutter
          ref: cf97bfbcb9f508a35cfdc451f4c2d19e30ad6b7c
          path: .flutter-sdk
          fetch-depth: 0
      - name: Select SDK
        run: echo "$GITHUB_WORKSPACE/.flutter-sdk/bin" >> "$GITHUB_PATH"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub get
        working-directory: example/protein_viewer
      - run: dart format --output=none --set-exit-if-changed lib/protein_viewer.dart lib/src/structure test/structure example/protein_viewer/lib
      - run: dart analyze lib/src/structure lib/protein_viewer.dart test/structure example/protein_viewer/lib
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test
